apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
  labels:
    name: nginx-proxy
spec:
  containers:
  - name: nginx-proxy
    image: nginx:1.25
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
